USE `brenda`;
SET SQL_SAFE_UPDATES = 0;
DELETE FROM `Km` WHERE `ec_num` = "1.1.1.47";
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=9.9, temp=30.0, substrate="NAD+", km=0.0003;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Rattus norvegicus", ph=NULL, temp=NULL, substrate="D-glucose 6-phosphate", km=0.0015;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="beta-D-glucose", km=0.0024;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=9.0, temp=NULL, substrate="NAD+", km=0.0028;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="D-Glucose-6-phosphate", km=0.0029;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="beta-D-glucose", km=0.0032;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="NADP+", km=0.0036;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="NADP+", km=0.0046;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="NAD+", km=0.0051;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.0051;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="D-Glucose-6-phosphate", km=0.0072;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=NULL, substrate="NADP+", km=0.0072;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.0076;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=NULL, substrate="D-Glucose-6-phosphate", km=0.0083;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.0093;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-glucose 6-phosphate", km=0.01;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="galactose 6-phosphate", km=0.01;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="galactose 6-phosphate", km=0.01;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Gluconobacter oxydans", ph=8.0, temp=25.0, substrate="NADP+", km=0.01;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="beta-D-glucose", km=0.011;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=7.5, temp=37.0, substrate="NADP+", km=0.013;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.018;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NADP+", km=0.018;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-glucose 6-phosphate", km=0.02;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NADP+", km=0.02;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=9.5, temp=30.0, substrate="NAD+", km=0.0212;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Nostoc sp.", ph=7.5, temp=NULL, substrate="NADP+", km=0.024;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=NULL, temp=NULL, substrate="D-glucose 6-phosphate", km=0.0255;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Mus musculus", ph=NULL, temp=NULL, substrate="NADP+", km=0.026;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.026;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.027;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="NADP+", km=0.028;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus thuringiensis serovar kurstaki", ph=9.0, temp=55.0, substrate="NADP+", km=0.03;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="NADP+", km=0.03;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="beta-D-glucose", km=0.032;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NADP+", km=0.037;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-galactose 6-phosphate", km=0.04;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-galactose 6-phosphate", km=0.04;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Mus musculus", ph=NULL, temp=NULL, substrate="D-glucose 6-phosphate", km=0.049;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="NAD+", km=0.05;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus amyloliquefaciens", ph=8.0, temp=37.0, substrate="NADP+", km=0.05;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=NULL, temp=NULL, substrate="NADP+", km=0.061;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=10.0, temp=37.0, substrate="NADP+", km=0.062;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=9.5, temp=30.0, substrate="NADP+", km=0.062;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=8.0, temp=25.0, substrate="NAD+", km=0.072;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NADP+", km=0.072;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NADP+", km=0.072;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NAD+", km=0.081;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=NULL, temp=NULL, substrate="NAD+", km=0.082;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NAD+", km=0.088;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="NAD+", km=0.09;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="NADP+", km=0.09;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NAD+", km=0.094;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NAD+", km=0.094;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-glucose 6-phosphate", km=0.1;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="NADP+", km=0.1;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=8.0, temp=25.0, substrate="NAD+", km=0.11;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoplasma acidophilum", ph=7.0, temp=55.0, substrate="NADP+", km=0.113;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Halobacterium salinarum", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=0.14;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=70.0, substrate="NADP+", km=0.14;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NAD+", km=0.15;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=65.0, substrate="NADP+", km=0.15;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=80.0, substrate="NADP+", km=0.15;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NAD+", km=0.16;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=6.5, temp=70.0, substrate="beta-D-glucose", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=70.0, substrate="D-glucose", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NAD+", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus thuringiensis serovar kurstaki", ph=9.0, temp=55.0, substrate="NAD+", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.17;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=0.18;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.19;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Halobacterium salinarum", ph=NULL, temp=NULL, substrate="NADP+", km=0.19;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NADP+", km=0.197;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NAD+", km=0.22;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=7.8, temp=23.0, substrate="NAD+", km=0.23;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=0.25;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus amyloliquefaciens", ph=8.0, temp=37.0, substrate="NAD+", km=0.25;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.25;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=7.8, temp=30.0, substrate="NADP+", km=0.26;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Nostoc sp.", ph=7.5, temp=NULL, substrate="NADP+", km=0.285;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="NAD+", km=0.293;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="2-deoxy-D-glucose 6-phosphate", km=0.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoproteus tenax", ph=7.0, temp=70.0, substrate="beta-D-glucose", km=0.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.31;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NAD+", km=0.33;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=8.0, temp=25.0, substrate="NAD+", km=0.344;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.36;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="NAD+", km=0.37;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=8.0, temp=25.0, substrate="NADP+", km=0.404;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.41;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.43;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=0.44;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="beta-D-glucose", km=0.44;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=9.8, temp=NULL, substrate="NAD+", km=0.44;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="NAD+", km=0.44;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=7.5, temp=70.0, substrate="NADP+", km=0.44;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.47;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Halobacterium salinarum", ph=NULL, temp=NULL, substrate="NADPH", km=0.49;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus thuringiensis serovar kurstaki", ph=9.0, temp=55.0, substrate="D-glucose", km=0.55;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=0.57;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=7.5, temp=70.0, substrate="NAD+", km=0.57;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="NAD+", km=0.67;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoproteus tenax", ph=7.0, temp=70.0, substrate="NADP+", km=0.7;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoproteus tenax", ph=7.0, temp=70.0, substrate="NAD+", km=0.86;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=0.86;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NAD+", km=0.99;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="2-deoxy-D-glucose 6-phosphate", km=1.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Gluconobacter oxydans", ph=NULL, temp=NULL, substrate="NADP+", km=1.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="NAD+", km=1.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=1.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=7.5, temp=70.0, substrate="NADP+", km=1.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=1.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=7.5, temp=70.0, substrate="NAD+", km=1.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=1.67;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NADP+", km=1.9;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="beta-D-glucose", km=2.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=70.0, substrate="NAD+", km=2.23;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=2.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Halobacterium salinarum", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=2.57;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="NAD+", km=2.64;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=2.7;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Burkholderia cepacia", ph=7.0, temp=70.0, substrate="beta-D-glucose", km=2.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose 6-phosphate", km=3.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose 6-phosphate", km=3.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=3.1;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="6-O-(beta-D-glucopyranosido)-beta-D-glucopyranoside", km=3.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=9.8, temp=NULL, substrate="gentiobiose", km=3.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=80.0, substrate="NAD+", km=3.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=9.5, temp=30.0, substrate="beta-D-glucose", km=3.38;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=4.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=4.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=4.1;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=6.5, temp=NULL, substrate="2-deoxy-D-glucose", km=4.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=4.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=4.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=4.35;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=4.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=9.0, temp=25.0, substrate="NAD+", km=4.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=6.5, temp=70.0, substrate="beta-D-glucose", km=4.59;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=70.0, substrate="D-glucose", km=4.59;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=4.6;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=9.0, temp=NULL, substrate="beta-D-glucose", km=4.6;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=6.5, temp=NULL, substrate="beta-D-glucose", km=4.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Gluconobacter oxydans", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=5.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose 6-phosphate", km=5.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose 6-phosphate", km=5.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Gluconobacter oxydans", ph=8.0, temp=25.0, substrate="D-glucose", km=5.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="D-glucose", km=5.1;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=5.13;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=5.49;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus amyloliquefaciens", ph=8.0, temp=37.0, substrate="D-glucose", km=5.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=65.0, substrate="NAD+", km=5.59;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="6-O-(beta-D-glucopyranosido)-beta-D-glucopyranoside", km=5.6;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Lysinibacillus sphaericus", ph=8.0, temp=25.0, substrate="D-glucose", km=6.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NAD+", km=7.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=7.07;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="D-glucose", km=7.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="NADP+", km=7.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=7.9;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="beta-D-glucose", km=8.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="beta-D-glucose", km=8.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="D-glucose", km=8.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoproteus tenax", ph=7.0, temp=70.0, substrate="xylose", km=8.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=8.16;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="beta-D-glucose", km=8.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="D-glucose", km=8.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=8.7;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=8.0, temp=25.0, substrate="beta-D-glucose", km=8.7;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=8.76;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=9.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=9.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=9.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="4-O-(beta-D-glucopyranosido)-beta-D-glucopyranoside", km=9.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=9.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=9.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Thermoplasma acidophilum", ph=7.0, temp=55.0, substrate="beta-D-glucose", km=10.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=10.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=10.24;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=10.29;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="4-O-(beta-D-glucopyranosido)-beta-D-glucopyranoside", km=11.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=11.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=9.8, temp=NULL, substrate="cellobiose", km=11.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=11.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=11.32;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=11.57;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=11.84;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=12.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=12.4;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-(3-phenylpropyl)-1,4-dihydropyridine-3-carboxamide", km=12.76;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=13.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=13.02;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=13.15;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=13.87;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Nostoc sp.", ph=7.5, temp=NULL, substrate="beta-D-glucose", km=14.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="beta-D-glucose", km=14.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=25.0, substrate="D-glucose", km=14.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-benzyl-3-carbamoylpyridin-1-ium chloride", km=14.78;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=14.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Nostoc sp.", ph=7.5, temp=NULL, substrate="beta-D-glucose", km=15.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=15.26;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=16.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=16.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="1-phenethyl-1,4-dihydropyridine-3-carboxamide", km=16.33;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=16.4;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus sp. (in: Bacteria)", ph=8.0, temp=25.0, substrate="D-glucose", km=17.126;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=17.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=17.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=17.4;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=7.0, temp=30.0, substrate="D-glucose", km=17.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=18.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="NADP+", km=18.9;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="beta-D-glucose", km=20.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=20.4;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="beta-D-galactose", km=22.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=24.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="2-deoxy-D-glucose 6-phosphate", km=25.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=29.2;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=NULL, temp=NULL, substrate="NAD+", km=30.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=33.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=6.5, temp=NULL, substrate="D-glucosamine", km=35.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="beta-D-glucose", km=40.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=7.8, temp=30.0, substrate="beta-D-glucose", km=42.9;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=44.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=9.5, temp=30.0, substrate="beta-D-glucose", km=47.22;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=9.0, temp=25.0, substrate="beta-D-glucose", km=47.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=7.8, temp=23.0, substrate="2-deoxy-beta-D-glucose", km=47.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=NULL, temp=NULL, substrate="NAD+", km=48.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="D-glucose", km=51.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=9.8, temp=NULL, substrate="D-glucose", km=51.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=55.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bacillus subtilis", ph=7.8, temp=30.0, substrate="beta-D-glucose", km=55.9;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=59.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=59.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=63.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Bos taurus", ph=NULL, temp=NULL, substrate="NADP+", km=63.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=65.8;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=9.0, temp=70.0, substrate="beta-D-xylose", km=68.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Sus scrofa", ph=9.9, temp=30.0, substrate="beta-D-glucose", km=70.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-xylose", km=70.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=72.5;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="D-xylose", km=76.3;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-glucose", km=80.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-glucose", km=80.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-xylose", km=80.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=81.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=NULL, temp=NULL, substrate="beta-D-glucose", km=85.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-xylose", km=100.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=NULL, temp=NULL, substrate="NADP+", km=105.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=109.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=118.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="D-xylose", km=125.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=9.8, temp=NULL, substrate="D-xylose", km=125.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=30.0, substrate="beta-D-glucose", km=135.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Corynebacterium sp.", ph=NULL, temp=NULL, substrate="D-xylose", km=148.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=175.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-xylose", km=200.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Saccharolobus solfataricus", ph=NULL, temp=NULL, substrate="beta-D-galactose", km=204.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=380.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-galactose", km=800.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose", km=1000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=1100.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=1400.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=2000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=2000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=10.0, temp=25.0, substrate="D-galactose", km=4000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=6.0, temp=37.0, substrate="D-glucose", km=4000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=4000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Priestia megaterium", ph=8.0, temp=37.0, substrate="D-glucose", km=5000.0;
INSERT IGNORE INTO `km` SET ec_num="1.1.1.47", speciesname="Oncorhynchus mykiss", ph=7.5, temp=25.0, substrate="D-galactose", km=10000.0;
SET SQL_SAFE_UPDATES = 1;
