# Generated by Django 3.1.3 on 2022-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_compound_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='product',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='reactant',
            field=models.JSONField(),
        ),
    ]
