# Generated by Django 3.1.3 on 2022-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20220715_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
