# Generated by Django 4.1 on 2022-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0003_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
