# Generated by Django 4.0.6 on 2022-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decarboxylation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'decarboxylation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'elimination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hydrolysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'hydrolysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mustcontain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mustcontain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'others',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'redox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'transfer',
                'managed': False,
            },
        ),
    ]
