# Generated by Django 3.1.3 on 2022-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactant', models.JSONField()),
                ('product', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
