# Generated by Django 4.1 on 2022-09-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreen', '0004_alter_query_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_num', models.CharField(blank=True, max_length=20, null=True)),
                ('ec_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'enzyme',
                'managed': False,
            },
        ),
    ]
